/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beasiswaku;

import java.awt.Desktop;
import java.awt.Frame;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Fida
 */
public class MainClass extends javax.swing.JFrame {

    public MainClass() {
        initComponents();
        setLocationRelativeTo(null);
//        setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jWelcome = new javax.swing.JLabel();
        jBest = new javax.swing.JLabel();
        btnHasil = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        jSmarts = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jWelcome.setForeground(new java.awt.Color(0, 0, 0));
        jWelcome.setText("WELCOME TO THE SCHOLARSHIP WEBSITE");

        jBest.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBest.setForeground(new java.awt.Color(0, 0, 0));
        jBest.setText("THE BEST SCHOLARSHIP PLATFORM");

        btnHasil.setBackground(new java.awt.Color(153, 204, 255));
        btnHasil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHasil.setForeground(new java.awt.Color(0, 0, 0));
        btnHasil.setText("Results");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        btnDaftar.setBackground(new java.awt.Color(153, 204, 255));
        btnDaftar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(0, 0, 0));
        btnDaftar.setText("Join Now");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        jSmarts.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        jSmarts.setForeground(new java.awt.Color(0, 0, 0));
        jSmarts.setText("Smart'S");

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/22.jpg"))); // NOI18N
        photo.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jWelcome)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDaftar)
                        .addGap(18, 18, 18)
                        .addComponent(btnHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jBest))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jSmarts)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jWelcome)
                .addGap(18, 18, 18)
                .addComponent(jBest)
                .addGap(7, 7, 7)
                .addComponent(jSmarts)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        setBounds(0, 0, 901, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
    //hsl
        if (Koneksi.konekKeDB() == null) {
            JOptionPane.showMessageDialog(this, ""
                    + "<html>"
                    + "Tidak dapat terhubung ke database<br>"
                    + "1. Cek apakah <b>server MySQL</b> sudah dijalankan.<br>"
                    + "2. Cek apakah Anda sudah membuat database"
                    + "</html>"); 
            try {
                Desktop.getDesktop().browse(new URL("http://localhost/phpmyadmin/").toURI());
                Thread.sleep(2000); 
                System.exit(0); 
            } catch (IOException | InterruptedException | URISyntaxException e) {
            }
            
        } else {
            SPK spk = new SPK();
            spk.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnHasilActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
        AddAlternatif a = new AddAlternatif(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnHasil;
    private javax.swing.JLabel jBest;
    private javax.swing.JLabel jSmarts;
    private javax.swing.JLabel jWelcome;
    private javax.swing.JLabel photo;
    // End of variables declaration//GEN-END:variables
}
